### ISSUE TITLE
How to modify the CSS real-time preview?

### ISSUE THREAD

**Issue by taoguangc** [stefanfrede/11st-starter-kit#151]
when I modify the css, I can’t preview it in real time.
For example, I add a class 'text-green-500' to some text in template.

**Comment by stefanfrede** [comment]
Hi! For that you have to reload the config. Sorry, so far I haven't found anything to automate this.

**Comment by ranjithrd** [comment]
Hey! I managed to get this working by commenting out `purge: ['./src/**/*.html', './src/**/*.md']` in `tailwind.config.js`. I don't think this is great for great environments, but while developing it's just far more convenient
