### ISSUE TITLE
missing default classes in dev view (localhost)?

### ISSUE THREAD

**Issue by stoqe** [stefanfrede/11st-starter-kit#154]
hello stefan. i love this starter so thanks for making it available

i'm having weird issues where lots of default tailwind classes seem to be missing from the dev view (localhost:8080) so i can't see them while building. but if i build and push live the classes are present as expected

any thoughts?

**Comment by stefanfrede** [comment]
👋 @stoqe, do you have a repo or something where I can reproduce this behaviour?

**Comment by stefanfrede** [comment]
I just ran into the exact same problem. I will have a look.
