### ISSUE TITLE
SASS support

### ISSUE THREAD

**Issue by azzamsa** [stefanfrede/11st-starter-kit#169]
Hi.

I am working hard to integrate SASS to `snowpack`. I stopped after spending ton of hours, and now looking for other options (`vite` or `plain rollup` or `parcel`). I open the issue here hoping there will be a solution. Because I don't find any `Eleventy + snowpack` but this repo.

The code here is worked well. But when I tried to integrate SASS. It doesn't work.
I have tried many possibilities. Nothing works. My last solution is  here:

I changed `styles/index.css` to `styles/index.scss` and ...

``` diff
// snowpack.config.js

   plugins: [
-    '@snowpack/plugin-postcss',
+    ['@snowpack/plugin-postcss', { input: ['.scss'], config: './postcss.config.js' }],
+    [
+      '@snowpack/plugin-sass',
+      {
+        native: 'true',
+        compilerOptions: { loadPath: ['./src/style/'] },
+      },
+    ],
```

``` diff
// postcss.config.js

-module.exports = {
-  plugins: {
-    '@tailwindcss/jit': {},
-    autoprefixer: {},
-  },
+module.exports = (ctx) => {
+  return {
+    // allow inline comment in SASS
+    syntax: 'postcss-scss',
+    plugins: [
+      require('@tailwindcss/jit')('tailwind.config.js'),
+      require('autoprefixer'),
+    ],
+  };
 };
 ```
 
 But the produced `index.css` still contains:
 
![image](https://user-images.githubusercontent.com/17734314/118901355-42375c00-b93d-11eb-9534-32caff9abdbe.png)

 the `@snowpack/plugin-postcss` doesn't change them to tailwindCSS clasess.

**Comment by stefanfrede** [comment]
I'm sorry, but I'm not a big fan of SASS and I stopped using it a long time ago.

For me plain CSS is working fine and I don't see the necessity to use a preprocessor.

Therefore I sadly will not be of much help.
