### ISSUE TITLE
Changing output directory

### ISSUE THREAD

**Issue by freshyill** [stefanfrede/11st-starter-kit#232]
I'd like to just use `dist` as my output directory during development, but if I try to change it, the local site never updates when I run `npm run dev` unless I restart. It seems like `dist` and `src/_site` are both being simultaneously, but I'm not sure why. 

Can you clarify how `dist` and `src/_site` are being used? Does this have something to do with Snowpack?

**Comment by stefanfrede** [comment]
11ty is building into `src/_site` and Snowpack is using this to build into `dist`.

Does this clarify things?

**Comment by freshyill** [comment]
Thanks, makes perfect sense!
