### ISSUE TITLE
Two refreshs are needed for changes to be applied in development

### ISSUE THREAD

**Issue by alexanderdavide** [stefanfrede/11st-starter-kit#348]
## Apparent bug
Developing on `npm run dev`, two refreshs are needed for changes to be applied.

Looking into `_site`, one can see that 11ty built the changes immediately but vite still serves the old bundle. My first thought was that vite may be too fast and therefore using the old files but then I realized vite should only be executed upon changes in root `_site` which 11ty apparently places the rebuild correctly into.

## Environment
vite: `2.8.4`
@11ty/eleventy: `1.0.0`,

## Reproduction steps
1. Clone `11st-starter-kit`
2. Make changes e. g. content of `index.md` or classes in `index.html`.
3. Save.
4. Recognize that changes are not applied.
5. Save or refresh browser.
6. See that changes are applied.

**Comment by alexanderdavide** [comment]
Seems like the problem only arises when developing in WSL. Everything works fine running on the host. I'll go ahead and close the issue.

**Comment by stefanfrede** [comment]
:wave:  @alexanderdavide,

Sorry for the late reply.

I'm aware of the issue and it is a race condition between 11ty and Vite. 

When Vite is faster then the page is getting refreshed before 11ty finished the build process.

It would be nice to be able to delay the start of Vite by a few milliseconds but sadly that is not possible at the moment.

As soon as I have time again I will look into some other options.

**Comment by alexanderdavide** [comment]
@stefanfrede

From what I've experienced, this issue only arises seldomly on the host. However, I'm used to develop in VS Code devcontainers. In WSL everything runs pretty slow which probably aggravates the problem and makes this setup hardly usable. Maybe this insight helps anybody or when further triaging the issue.
