### ISSUE TITLE
Install and Run Issues

### ISSUE THREAD

**Issue by aaronstezycki** [stefanfrede/11st-starter-kit#445]
Upon installing and running the starter, it fails and complains that it cannot find 'markdown it anchor'.

Ive noticed that both 'markdown-it' and 'markdown-it-anchor' are both not in the package.json as devDependencies.

**Comment by aaronstezycki** [comment]
... and eleventy navigation.

**Comment by aaronstezycki** [comment]
... and eleventy RSS

**Comment by stefanfrede** [comment]
Sorry, just stumbled over your issue :flushed:

I updated the dependencies and ran an `npm run setup` without problems.

Please reopen if I missed something.
