### ISSUE TITLE
Update content with Service Worker

### ISSUE THREAD

**Issue by budparr** [stefanfrede/11st-starter-kit#54]
I'm really enjoying how you've put this starter together. I'm pushing changes to Netlify and am not seeing content updates because of the service worker. Shouldn't that version change? I see you're using nanoid, but not sure I understand how it updates the service worker on a content change. Or perhaps I'm missing something.

**Comment by stefanfrede** [comment]
Thank you very much!

With nanoid I generate a unique id which is used here: https://github.com/stefanfrede/11st-starter-kit/blob/main/src/service-worker.liquid#L5.

So, the idea is that with every build there is a new unique id for the service worker and this should invalidate the already registered one.

Does this help?

**Comment by budparr** [comment]
Hmm. That doesn't seem to be happening for me. But I'll work up an example soon to test. Thanks!

**Comment by stefanfrede** [comment]
Please share your findings.

I will close the ticket for now.
