### ISSUE TITLE
[snowpack] Package "tailwindcss/base" not found. Have you installed it?

### ISSUE THREAD

**Issue by waynehoover** [stefanfrede/11st-starter-kit#7]
From a clean install I did `npm i` then `npm start` and I get this error `[snowpack] Package "tailwindcss/base" not found. Have you installed it?`

**Comment by stefanfrede** [comment]
I just did a clean install and everything seems to be fine.

Can you please update and check again. Thx!

**Comment by stefanfrede** [comment]
I removed the `prepare` script which should remove the error during installation.
